"""Add coordinates to base model

Revision ID: ce66605f8b58
Revises: 001
Create Date: 2025-08-25 00:33:09.024364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce66605f8b58'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('air_quality_sensors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('air_quality_sensors', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('energy_grid_sensors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('energy_grid_sensors', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('noise_sensors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('noise_sensors', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('parking_sensors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('parking_sensors', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('public_transport_trackers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('public_transport_trackers', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('smart_meters', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('smart_meters', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('street_lights', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('street_lights', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('surveillance_cameras', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('surveillance_cameras', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('traffic_sensors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('traffic_sensors', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('waste_bins', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('waste_bins', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('water_quality_sensors', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('water_quality_sensors', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('weather_stations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('weather_stations', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_stations', 'longitude')
    op.drop_column('weather_stations', 'latitude')
    op.drop_column('water_quality_sensors', 'longitude')
    op.drop_column('water_quality_sensors', 'latitude')
    op.drop_column('waste_bins', 'longitude')
    op.drop_column('waste_bins', 'latitude')
    op.drop_column('traffic_sensors', 'longitude')
    op.drop_column('traffic_sensors', 'latitude')
    op.drop_column('surveillance_cameras', 'longitude')
    op.drop_column('surveillance_cameras', 'latitude')
    op.drop_column('street_lights', 'longitude')
    op.drop_column('street_lights', 'latitude')
    op.drop_column('smart_meters', 'longitude')
    op.drop_column('smart_meters', 'latitude')
    op.drop_column('public_transport_trackers', 'longitude')
    op.drop_column('public_transport_trackers', 'latitude')
    op.drop_column('parking_sensors', 'longitude')
    op.drop_column('parking_sensors', 'latitude')
    op.drop_column('noise_sensors', 'longitude')
    op.drop_column('noise_sensors', 'latitude')
    op.drop_column('energy_grid_sensors', 'longitude')
    op.drop_column('energy_grid_sensors', 'latitude')
    op.drop_column('air_quality_sensors', 'longitude')
    op.drop_column('air_quality_sensors', 'latitude')
    # ### end Alembic commands ###
